@node Top
@top Top

Simple table with caption:

@float
@multitable {Right} {Left} {Center} {Default} 
@headitem 
Right
 @tab Left
 @tab Center
 @tab Default
@item 
12
 @tab 12
 @tab 12
 @tab 12
@item 
123
 @tab 123
 @tab 123
 @tab 123
@item 
1
 @tab 1
 @tab 1
 @tab 1
@end multitable
@caption{Demonstration of simple table syntax.}
@end float
Simple table without caption:

@multitable {Right} {Left} {Center} {Default} 
@headitem 
Right
 @tab Left
 @tab Center
 @tab Default
@item 
12
 @tab 12
 @tab 12
 @tab 12
@item 
123
 @tab 123
 @tab 123
 @tab 123
@item 
1
 @tab 1
 @tab 1
 @tab 1
@end multitable

Simple table indented two spaces:

@float
@multitable {Right} {Left} {Center} {Default} 
@headitem 
Right
 @tab Left
 @tab Center
 @tab Default
@item 
12
 @tab 12
 @tab 12
 @tab 12
@item 
123
 @tab 123
 @tab 123
 @tab 123
@item 
1
 @tab 1
 @tab 1
 @tab 1
@end multitable
@caption{Demonstration of simple table syntax.}
@end float
Multiline table with caption:

@float
@multitable @columnfractions 0.15 0.14 0.16 0.35 
@headitem 
Centered Header
 @tab Left Aligned
 @tab Right Aligned
 @tab Default aligned
@item 
First
 @tab row
 @tab 12.0
 @tab Example of a row that spans multiple lines.
@item 
Second
 @tab row
 @tab 5.0
 @tab Here's another one. Note the blank line between rows.
@end multitable
@caption{Here's the caption. It may span multiple lines.}
@end float
Multiline table without caption:

@multitable @columnfractions 0.15 0.14 0.16 0.35 
@headitem 
Centered Header
 @tab Left Aligned
 @tab Right Aligned
 @tab Default aligned
@item 
First
 @tab row
 @tab 12.0
 @tab Example of a row that spans multiple lines.
@item 
Second
 @tab row
 @tab 5.0
 @tab Here's another one. Note the blank line between rows.
@end multitable

Table without column headers:

@multitable {123} {123} {123} {123} 
@item 
12
 @tab 12
 @tab 12
 @tab 12
@item 
123
 @tab 123
 @tab 123
 @tab 123
@item 
1
 @tab 1
 @tab 1
 @tab 1
@end multitable

Multiline table without column headers:

@multitable @columnfractions 0.15 0.14 0.16 0.35 
@item 
First
 @tab row
 @tab 12.0
 @tab Example of a row that spans multiple lines.
@item 
Second
 @tab row
 @tab 5.0
 @tab Here's another one. Note the blank line between rows.
@end multitable
