flags:
  pandoc:
    trypandoc: false
    https: true
    embed_data_files: true
    old-locale: false
    network-uri: true
  pandoc-citeproc:
    bibutils: true
    embed_data_files: true
    unicode_collation: false
    test_citeproc: false
    debug: false
packages:
- '..'
- location:
    git: https://github.com/jgm/pandoc-citeproc.git
    commit: cebeadd1efdbdd4d3059a25386c239530a73f106
  extra-dep: true
extra-deps:
- texmath-0.9
- doctemplates-0.1.0.2
- pandoc-types-1.17.0.4
- skylighting-0.1.1.4
resolver: lts-7.14
