flags:
  pandoc:
    trypandoc: false
    https: true
    embed_data_files: true
    old-locale: false
    network-uri: true
  pandoc-citeproc:
    bibutils: true
    embed_data_files: true
    unicode_collation: false
    test_citeproc: false
    debug: false
packages:
- '..'
extra-deps:
- pandoc-citeproc-0.10.3
- texmath-0.9
- doctemplates-0.1.0.2
- pandoc-types-1.17.0.4
- skylighting-0.1.1
resolver: lts-7.14
