$if(has-tables)$
.\"t
$endif$
.TH "$title$" "$section$" "$date$" "$footer$" "$header$"
$for(header-includes)$
$header-includes$
$endfor$
$for(include-before)$
$include-before$
$endfor$
$body$
$for(include-after)$
$include-after$
$endfor$
$if(author)$
.SH AUTHORS
$for(author)$$author$$sep$; $endfor$.
$endif$
