#!/bin/sh -e
# runs pandoc to convert latex to markdown

pathfind () { # portable which(1), code taken from Debian Developer's Reference
    OLDIFS="$IFS"
    IFS=:
    for _p in $PATH; do
        if [ -x "$_p/$*" ]; then
            IFS="$OLDIFS"
            return 0
        fi
    done
    IFS="$OLDIFS"
    return 1
}

for p in pandoc; do
    pathfind $p || {
        echo >&2 "You need '$p' to use this program!"
        exit 1
    }
done

ALL="$*"
ARGS=${ALL%%-- *}
REST=${ALL#$ARGS}

REST=${REST#--}
PANDOC_OPTS=${REST:-$PANDOC_OPTS}

iconv -t utf-8 $ARGS | pandoc $PANDOC_OPTS -r latex -w markdown -s | \
    iconv -f utf-8
