#!/bin/sh -e
# runs pandoc to convert latex to markdown

for p in pandoc; do
	which $p >/dev/null 2>&1 || {
		echo >&2 "You need '$p' to use this program!"
		exit 1
	}
done

iconv -t utf-8 $* | pandoc $PANDOC_OPTS -r latex -w markdown -s | iconv -f utf-8
