flags:
  pandoc:
    trypandoc: false
    embed_data_files: true
  QuickCheck:
    old-random: false
packages:
- '.'
extra-deps:
- skylighting-core-0.12.2
- skylighting-0.12.2
- doctemplates-0.10.0.1
- emojis-0.1.2
- doclayout-0.3.1.1
- lpeg-1.0.2
- hslua-2.1.0
- hslua-aeson-2.1.0
- hslua-classes-2.1.0
- hslua-core-2.1.0
- hslua-marshalling-2.1.0
- hslua-module-doclayout-1.0.2
- hslua-module-path-1.0.1
- hslua-module-system-1.0.1
- hslua-module-text-1.0.1
- hslua-module-version-1.0.1
- hslua-objectorientation-2.1.0
- hslua-packaging-2.1.0
- lua-2.1.0
- lua-arbitrary-1.0.0
- tasty-hslua-1.0.1
- tasty-lua-1.0.1
- pandoc-lua-marshal-0.1.5
- pandoc-types-1.22.1
- aeson-pretty-0.8.9
- unicode-transforms-0.4.0@rev:1
- unicode-data-0.3.0
- texmath-0.12.4
- commonmark-pandoc-0.2.1.2
- ipynb-0.2
- git: https://github.com/jgm/citeproc.git
  commit: 32fcf268d8bac2825eddd3c51a9112112e5eaadb
- git: https://github.com/jgm/commonmark-hs.git
  commit: 02f573527d537a3f9e037d460638d1e4f8a5ca9b
  subdirs: [commonmark, commonmark-extensions]
ghc-options:
   "$locals": -fhide-source-paths -Wno-missing-home-modules
resolver: lts-18.10
nix:
  packages: [zlib]
