flags:
  pandoc:
    trypandoc: false
    embed_data_files: true
  QuickCheck:
    old-random: false
packages:
- '.'
extra-deps:
- skylighting-core-0.12.2
- skylighting-0.12.2
- doctemplates-0.10.0.1
- emojis-0.1.2
- doclayout-0.3.1.1
- lpeg-1.0.1
- hslua-2.0.1
- hslua-aeson-2.0.1
- hslua-classes-2.0.0
- hslua-core-2.0.0.2
- hslua-marshalling-2.0.1
- hslua-module-path-1.0.0
- hslua-module-system-1.0.0
- hslua-module-text-1.0.0
- hslua-module-version-1.0.0
- hslua-objectorientation-2.0.1
- hslua-packaging-2.0.0
- lua-2.0.2
- tasty-hslua-1.0.0
- tasty-lua-1.0.0
- pandoc-lua-marshal-0.1.3.1
- pandoc-types-1.22.1
- aeson-pretty-0.8.9
- unicode-transforms-0.4.0
- unicode-data-0.2.0
- texmath-0.12.4
- commonmark-0.2.1.1
- commonmark-extensions-0.2.3
- commonmark-pandoc-0.2.1.2
- citeproc-0.6.0.1
- ipynb-0.2
ghc-options:
   "$locals": -fhide-source-paths -Wno-missing-home-modules
resolver: lts-18.10
nix:
  packages: [zlib]


