flags:
  pandoc:
    embed_data_files: true
  QuickCheck:
    old-random: false
allow-newer: true
allow-newer-deps:
  # This needs zip-archive 0.5
  - hslua-module-zip
  # These need to allow doclayout 0.6
  - gridtables
  - djot
  - hslua-module-doclayout
packages:
- '.'
- 'pandoc-cli'
- 'pandoc-lua-engine'
- 'pandoc-server'
extra-deps:
- hslua-2.5.0
- hslua-module-doclayout-1.2.1.1
- hslua-module-path-1.2.0
- hslua-module-text-1.2.0
- hslua-module-system-1.3.0
- hslua-module-version-1.2.0.1
- hslua-module-zip-1.2.1
- hslua-objectorientation-2.5.0
- hslua-packaging-2.4.1
- hslua-typing-0.2.0
- skylighting-format-blaze-html-0.1.2.2
- skylighting-0.15
- skylighting-core-0.15
- typst-symbols-0.3
- zip-archive-0.5
- citeproc-0.14
- doclayout-0.6
- doctemplates-0.11.1
- asciidoc-0.1.1
- texmath-0.13.3
- commonmark-0.3.0.1
- commonmark-pandoc-0.3.0.1
- commonmark-extensions-0.2.7.2
- git: https://github.com/jgm/typst-hs
  commit: a2ebb326923ff7c3e8bfe99d24a6e62d2a3984ee
- git: https://github.com/jgm/djoths
  commit: 20549c6b7466cfbf8c3645ddfac68e223ca113f3
# needed because not yet in nixpkgs:
- pandoc-types-1.23.1.2
# needed because not yet in nixpkgs:
- emojis-0.1.5
ghc-options:
   "$locals": -fhide-source-paths -Wno-missing-home-modules
resolver: lts-24.51
nix:
  packages:
  - pkg-config
  - zlib
