flags:
  pandoc:
    embed_data_files: true
  QuickCheck:
    old-random: false
packages:
- '.'
- 'pandoc-cli'
- 'pandoc-lua-engine'
- 'pandoc-server'
extra-deps:
- tls-2.1.7
- skylighting-core-0.14.6
- skylighting-0.14.6
- skylighting-format-typst-0.1
- texmath-0.12.8.13
- typst-0.6.2
- citeproc-0.8.1.3
- commonmark-extensions-0.2.6
- commonmark-pandoc-0.2.3
ghc-options:
   "$locals": -fhide-source-paths -Wno-missing-home-modules
resolver: lts-23.0
nix:
  packages:
  - pkg-config
  - zlib
