flags:
  pandoc:
    trypandoc: false
    https: true
    embed_data_files: false
    old-locale: false
    network-uri: true
packages:
- '.'
extra-deps:
- hslua-0.5.0
- hslua-aeson-0.1.0.3
- skylighting-0.3.2
- texmath-0.9.4
- executable-path-0.0.3.1
resolver: lts-8.4
