flags:
  pandoc:
    embed_data_files: true
  QuickCheck:
    old-random: false
packages:
- '.'
- 'pandoc-cli'
- 'pandoc-lua-engine'
- 'pandoc-server'
extra-deps:
- hslua-2.4.0
- hslua-module-system-1.2.3
- hslua-objectorientation-2.4.0
- hslua-packaging-2.3.2
- typst-symbols-0.1.9.1
- citeproc-0.12
- typst-0.8.1
- texmath-0.13.0.2
- djot-0.1.2.4
- git: https://github.com/jgm/asciidoc-hs.git
  commit: 4976e8b493808191358f4fadbe496e0a7c8e0fd1
ghc-options:
   "$locals": -fhide-source-paths -Wno-missing-home-modules
resolver: lts-24.20
nix:
  packages:
  - pkg-config
  - zlib
