flags:
  pandoc:
    embed_data_files: true
  QuickCheck:
    old-random: false
packages:
- '.'
- 'pandoc-cli'
- 'pandoc-lua-engine'
- 'pandoc-server'
extra-deps:
- tls-2.1.7
- skylighting-core-0.14.6
- skylighting-0.14.6
- skylighting-format-typst-0.1
- commonmark-extensions-0.2.6
- commonmark-pandoc-0.2.3
- typst-0.7
- git: https://github.com/jgm/citeproc.git
  commit: cf5542df8f21085bbfd794eaa5cc40abc605637b
- git: https://github.com/jgm/texmath.git
  commit: aa0cffc32fd6d3d9e0f219b8583141de99b54a36

ghc-options:
   "$locals": -fhide-source-paths -Wno-missing-home-modules
resolver: lts-23.0
nix:
  packages:
  - pkg-config
  - zlib
