flags:
  pandoc:
    trypandoc: false
    embed_data_files: true
  pandoc-citeproc:
    bibutils: true
    embed_data_files: true
    unicode_collation: false
    test_citeproc: false
    debug: false
packages:
- '.'
# See https://github.com/haskell-foundation/foundation/pull/503
# We can go back to released foundation when this is fixed.
- location:
    git: https://github.com/jgm/foundation
    commit: '4294e39'
  subdirs:
  - foundation
  extra-dep: true
extra-deps:
- github: jgm/pandoc-citeproc
  commit: 4b467c62af17ddfc739933891c5ea2291a6b9b76
- haddock-library-1.7.0
- HsYAML-0.1.1.2
- yaml-0.11.0.0
- libyaml-0.1.0.0
- hslua-1.0.1
- hslua-module-text-0.2.0
ghc-options:
   "$locals": -fhide-source-paths -XNoImplicitPrelude
resolver: lts-12.23
