flags:
  pandoc:
    embed_data_files: true
  QuickCheck:
    old-random: false
packages:
- '.'
- 'pandoc-cli'
- 'pandoc-lua-engine'
- 'pandoc-server'
extra-deps:
- skylighting-core-0.13.2
- skylighting-0.13.2
- skylighting-format-context-0.1.0.1
- skylighting-format-ansi-0.1
- skylighting-format-latex-0.1
- skylighting-format-blaze-html-0.1.1
- gridtables-0.1.0.0
- hslua-cli-1.2.0
- hslua-list-1.1.0
- hslua-module-text-1.0.3
- hslua-module-zip-1.0.0
- jira-wiki-markup-1.5.0
- mime-types-0.1.1.0
- doctemplates-0.11
- commonmark-extensions-0.2.3.3
- git: https://github.com/jgm/texmath
  commit: 1a77db688bd3285228299e5aeefc93d6c0d8c0b9
- git: https://github.com/jgm/citeproc
  commit: a8b7748537401d6c9749406a49df7008cea8c7f2

ghc-options:
   "$locals": -fhide-source-paths -Wno-missing-home-modules
resolver: lts-20.6
nix:
  packages: [zlib]
