flags:
  pandoc:
    embed_data_files: true
  QuickCheck:
    old-random: false
packages:
- '.'
- 'pandoc-cli'
- 'pandoc-server'
extra-deps:
- skylighting-core-0.13
- skylighting-0.13
- skylighting-format-ansi-0.1
- skylighting-format-latex-0.1
- skylighting-format-blaze-html-0.1.1
- hslua-2.2.1
- hslua-aeson-2.2.1
- hslua-cli-1.2.0
- hslua-classes-2.2.0
- hslua-core-2.2.1
- hslua-marshalling-2.2.1
- hslua-module-version-1.0.3
- hslua-objectorientation-2.2.1
- hslua-packaging-2.2.1
- lua-2.2.1
- mime-types-0.1.1.0
- doclayout-0.4
- doctemplates-0.10.0.2
- citeproc-0.8.0.1
- git: https://github.com/jgm/commonmark-hs
  commit: 4f4fbe277044de0724dd0828a45311ab1413e30b
  subdirs: [commonmark-extensions]
- git: https://github.com/quarto-dev/gridtables
  commit: 1dbf2ad311fc7b2d9aded51eb263067b6ff3ae28
- git: https://github.com/jgm/texmath
  commit: 0fb6bf8cff1a424cdbc91713c30e59dbb979211c
ghc-options:
   "$locals": -fhide-source-paths -Wno-missing-home-modules
resolver: lts-19.21
nix:
  packages: [zlib]
