flags:
  pandoc:
    embed_data_files: true
  QuickCheck:
    old-random: false
packages:
- '.'
- 'pandoc-cli'
- 'pandoc-lua-engine'
- 'pandoc-server'
extra-deps:
- hslua-2.4.0
- hslua-module-system-1.2.3
- hslua-objectorientation-2.4.0
- hslua-packaging-2.3.2
- typst-symbols-0.1.9.1
- citeproc-0.12
- texmath-0.13.0.2
- djot-0.1.2.4
- git: https://github.com/jgm/asciidoc-hs.git
  commit: c2b4852e0002a7995793ec0e3c44b723a85a2ca2
- git: https://github.com/jgm/typst-hs.git
  commit: 9b10ff32492304867b6cc410db6e843c2c9b913b
- git: https://github.com/jgm/citeproc.git
  commit: 777a916be683a40e9b5e17da25816917b6fb1208
ghc-options:
   "$locals": -fhide-source-paths -Wno-missing-home-modules
resolver: lts-24.20
nix:
  packages:
  - pkg-config
  - zlib
