flags:
  pandoc:
    embed_data_files: true
  QuickCheck:
    old-random: false
packages:
- '.'
- 'pandoc-cli'
- 'pandoc-lua-engine'
- 'pandoc-server'
extra-deps:
- hslua-cli-1.4.1
- hslua-module-zip-1.1.0
- hslua-repl-0.1.1
- tls-1.7.0
- crypton-connection-0.3.1
- crypton-x509-1.7.6
- crypton-x509-store-1.6.9
- crypton-x509-system-1.6.7
- crypton-x509-validation-1.6.12
- http-client-tls-0.3.6.2
- commonmark-0.2.3
- typst-symbols-0.1.2
- toml-parser-1.1.1.0
- pandoc-types-1.23.0.1
- skylighting-0.13.4
- xml-conduit-1.9.1.3
- commonmark-extensions-0.2.3.5
- git: https://github.com/jgm/typst-hs
  commit: aa72087f21ee6dd2d906df8c3fd55af0778c0c13
- git: https://github.com/jgm/skylighting
  commit: 2d3fe8a9aa18df60b8dc30af0f9e303320747ea6
  subdirs: [skylighting-core]

ghc-options:
   "$locals": -fhide-source-paths -Wno-missing-home-modules
resolver: lts-21.0
nix:
  packages:
  - pkg-config
  - zlib
