flags:
  pandoc:
    embed_data_files: true
  QuickCheck:
    old-random: false
packages:
- '.'
- 'pandoc-cli'
- 'pandoc-lua-engine'
- 'pandoc-server'
extra-deps:
- hslua-cli-1.4.1
- hslua-module-zip-1.1.0
- hslua-repl-0.1.1
- lpeg-1.1.0
- crypton-connection-0.3.1
- crypton-x509-1.7.6
- crypton-x509-store-1.6.9
- crypton-x509-system-1.6.7
- crypton-x509-validation-1.6.12
- http-client-tls-0.3.6.3
- typst-symbols-0.1.4
- toml-parser-1.3.0.0
- skylighting-core-0.14.1
- skylighting-0.14.1
- skylighting-format-blaze-html-0.1.1.1
- texmath-0.12.8.4
- tls-1.9.0
- commonmark-0.2.4
- git: https://github.com/jgm/typst-hs
  commit: 2a92d6b61b077ad6eaff857f45aa50004658082e
- git: https://github.com/jgm/commonmark-hs
  subdirs: [commonmark-extensions, commonmark-pandoc]
  commit: 0c4807c92b94b1b5ac0f0845daac276ab9d3495f

ghc-options:
   "$locals": -fhide-source-paths -Wno-missing-home-modules
resolver: lts-21.7
nix:
  packages:
  - pkg-config
  - zlib
