flags:
  pandoc:
    trypandoc: false
    embed_data_files: true
  QuickCheck:
    old-random: false
packages:
- '.'
extra-deps:
- skylighting-core-0.12.1
- skylighting-0.12.1
- doctemplates-0.10
- emojis-0.1.2
- doclayout-0.3.1.1
- lpeg-1.0.1
- hslua-2.0.1
- hslua-classes-2.0.0
- hslua-core-2.0.0.2
- hslua-marshalling-2.0.1
- hslua-module-path-1.0.0
- hslua-module-system-1.0.0
- hslua-module-text-1.0.0
- hslua-module-version-1.0.0
- hslua-objectorientation-2.0.1
- hslua-packaging-2.0.0
- lua-2.0.2
- tasty-hslua-1.0.0
- tasty-lua-1.0.0
- pandoc-types-1.22.1
- commonmark-0.2.1.1
- commonmark-extensions-0.2.2
- citeproc-0.6
- aeson-pretty-0.8.9
- ipynb-0.1.0.2
- texmath-0.12.3.3
- git: https://github.com/tarleb/hslua-pandoc-types.git
  commit: 56387e543c48cc5518a77c2a271ff211653f2a36
ghc-options:
   "$locals": -fhide-source-paths -Wno-missing-home-modules
resolver: lts-18.10
nix:
  packages: [zlib]
