flags:
  pandoc:
    trypandoc: false
    https: true
    embed_data_files: false
    old-locale: false
    network-uri: true
packages:
- '.'
extra-deps:
- data-default-0.6.0
- data-default-instances-base-0.1.0
resolver: lts-6.1
