flags:
  pandoc:
    embed_data_files: true
  QuickCheck:
    old-random: false
packages:
- '.'
- 'pandoc-cli'
- 'pandoc-lua-engine'
- 'pandoc-server'
extra-deps:
- skylighting-core-0.13.1.1
- skylighting-0.13.1.1
- skylighting-format-ansi-0.1
- skylighting-format-latex-0.1
- skylighting-format-blaze-html-0.1.1
- gridtables-0.1.0.0
- hslua-2.2.1
- hslua-aeson-2.2.1
- hslua-cli-1.2.0
- hslua-classes-2.2.0
- hslua-core-2.2.1
- hslua-list-1.1.0
- hslua-marshalling-2.2.1
- hslua-module-version-1.0.3
- hslua-module-zip-1.0.0
- hslua-objectorientation-2.2.1
- hslua-packaging-2.2.1
- lua-2.2.1
- mime-types-0.1.1.0
- doclayout-0.4
- doctemplates-0.10.0.2
- commonmark-extensions-0.2.3.3
- texmath-0.12.5.4
- git: https://github.com/jgm/citeproc
  commit: cb54223919ecd327250f1b167e4e0c61473f402e

ghc-options:
   "$locals": -fhide-source-paths -Wno-missing-home-modules
resolver: lts-19.21
nix:
  packages: [zlib]
