flags:
  pandoc:
    trypandoc: false
    embed_data_files: true
    static: false
  pandoc-citeproc:
    bibutils: true
    embed_data_files: true
    unicode_collation: false
    test_citeproc: false
    debug: false
packages:
- '.'
extra-deps:
# - pandoc-types-1.20
# better-tables
- git: https://github.com/jgm/pandoc-types
  commit: 4acb0e50f10d8f41f94c0973384d63f06d0b9ffd
- git: https://github.com/jgm/pandoc-citeproc
  commit: 2e6fe791ec5293acc925c2ccbe79c9c10d2b7e07
- texmath-0.12.0.2
- haddock-library-1.8.0
- skylighting-0.8.3.2
- skylighting-core-0.8.3.2
- regex-pcre-builtin-0.95.0.8.8.35
- doclayout-0.3
- emojis-0.1
- hslua-1.1.0
- jira-wiki-markup-1.3.0
- HsYAML-0.2.0.0
- HsYAML-aeson-0.2.0.0
- doctemplates-0.8.2
ghc-options:
   "$locals": -fhide-source-paths -Wno-missing-home-modules
resolver: lts-14.6
