flags:
  pandoc:
    trypandoc: false
    https: true
    embed_data_files: false
    old-locale: false
    network-uri: true
packages:
- '.'
extra-deps:
- data-default-0.6.0
- http-client-0.5.0
- http-client-tls-0.3.0
- data-default-instances-base-0.1.0.1
resolver: nightly-2016-07-11
