flags:
  pandoc:
    embed_data_files: true
  QuickCheck:
    old-random: false
packages:
- '.'
- 'pandoc-cli'
- 'pandoc-lua-engine'
- 'pandoc-server'
extra-deps:
- gridtables-0.1.0.0
- hslua-2.3.0
- hslua-aeson-2.3.0.1
- hslua-classes-2.3.0
- hslua-cli-1.4.1
- hslua-core-2.3.1
- hslua-list-1.1.1
- hslua-marshalling-2.3.0
- hslua-module-doclayout-1.1.0
- hslua-module-path-1.1.0
- hslua-module-system-1.1.0.1
- hslua-module-text-1.1.0.1
- hslua-module-version-1.1.0
- hslua-module-zip-1.1.0
- hslua-objectorientation-2.3.0
- hslua-packaging-2.3.0
- hslua-repl-0.1.1
- hslua-typing-0.1.0
- jira-wiki-markup-1.5.1
- lua-2.3.1
- lua-arbitrary-1.0.1.1
- lpeg-1.0.4
- mime-types-0.1.1.0
- doctemplates-0.11
- citeproc-0.8.1
- pandoc-types-1.23
- pandoc-lua-marshal-0.2.2
- commonmark-pandoc-0.2.1.3
- skylighting-0.13.2.1
- skylighting-core-0.13.2.1
- skylighting-format-context-0.1.0.2
- tasty-lua-1.1.0
- tasty-hslua-1.1.0
- zip-archive-0.4.3
- commonmark-extensions-0.2.3.4
- doclayout-0.4.0.1
- git: https://github.com/jgm/texmath
  commit: 5b337e57b80831b624f52dd250ab5d612ee94b88

ghc-options:
   "$locals": -fhide-source-paths -Wno-missing-home-modules
resolver: lts-20.6
nix:
  packages: [zlib]
