flags:
  pandoc:
    trypandoc: false
    https: true
    embed_data_files: false
    old-locale: false
    network-uri: true
packages:
- '.'
extra-deps:
- texmath-0.9
- doctemplates-0.1.0.2
- pandoc-types-1.17.0.4
- skylighting-0.1.1.2
- blaze-html-0.9.0.1
- blaze-markup-0.8.0.0
resolver: lts-7.14
