flags:
  pandoc:
    trypandoc: false
    embed_data_files: true
  pandoc-citeproc:
    bibutils: true
    embed_data_files: true
    unicode_collation: false
    test_citeproc: false
    debug: false
packages:
- '.'
extra-deps:
# - pandoc-citeproc-0.16.2
- git: https://github.com/jgm/pandoc-citeproc
  commit: 6d62678ece91bbb4fe4f5a99695006e1d53c3bae
- git: https://github.com/tarleb/pandoc-types
  commit: a087b0174a597b92c5fec4d633c46887c188b496
- ipynb-0.1
- cmark-gfm-0.2.0
- hslua-1.0.3.1
- hslua-module-system-0.2.0
- tasty-lua-0.2.0
- skylighting-core-0.8.2
- skylighting-0.8.2
- doctemplates-0.3.0.1
ghc-options:
   "$locals": -Wall -fno-warn-unused-do-bind -Wincomplete-record-updates -Wnoncanonical-monad-instances -Wnoncanonical-monadfail-instances -Wincomplete-uni-patterns -Widentities -Wcpp-undef -fhide-source-paths -Wno-missing-home-modules
resolver: lts-13.17
