flags:
  pandoc:
    embed_data_files: true
  QuickCheck:
    old-random: false
packages:
- '.'
- 'pandoc-cli'
- 'pandoc-lua-engine'
- 'pandoc-server'
extra-deps:
- hslua-cli-1.4.1
- hslua-module-zip-1.1.0
- hslua-repl-0.1.1
- tls-1.8.0
- crypton-connection-0.3.1
- crypton-x509-1.7.6
- crypton-x509-store-1.6.9
- crypton-x509-system-1.6.7
- crypton-x509-validation-1.6.12
- http-client-tls-0.3.6.3
- typst-symbols-0.1.4
- toml-parser-1.3.0.0
- typst-0.3.2.0
- texmath-0.12.8.1
- skylighting-core-0.14
- skylighting-0.14
ghc-options:
   "$locals": -fhide-source-paths -Wno-missing-home-modules
resolver: lts-21.7
nix:
  packages:
  - pkg-config
  - zlib
