flags:
  pandoc:
    trypandoc: false
    embed_data_files: true
  QuickCheck:
    old-random: false
packages:
- '.'
extra-deps:
- skylighting-core-0.12
- skylighting-0.12
- doctemplates-0.10
- git: https://github.com/jgm/texmath.git
  commit: 0b6febf13cd229e178fccf7216c0548a3b81cf8c
- git: https://github.com/jgm/pandoc-types.git
  commit: aed20ed845edf98110995217d66d4627a1824eea
- git: https://github.com/jgm/commonmark-hs.git
  commit: e1a2710cdddf570c458a60360fc1951fa282592a
  subdirs:
  - commonmark-pandoc
- git: https://github.com/jgm/citeproc.git
  commit: d301ff5ebd3dad5476d70463b0fc9ffe30161ecf
ghc-options:
   "$locals": -fhide-source-paths -Wno-missing-home-modules
resolver: lts-18.10
nix:
  packages: [zlib]


