flags:
  pandoc:
    embed_data_files: true
  QuickCheck:
    old-random: false
packages:
- '.'
- 'pandoc-cli'
- 'pandoc-lua-engine'
- 'pandoc-server'
extra-deps:
- tls-2.1.7
- skylighting-core-0.14.6
- skylighting-0.14.6
- skylighting-format-typst-0.1
- citeproc-0.8.1.3
- commonmark-extensions-0.2.6
- commonmark-pandoc-0.2.3
- git: https://github.com/jgm/typst-hs.git
  commit: 66fa2666c4ae642e1d231010f4fe1621430af346
- git: https://github.com/jgm/texmath.git
  commit: b3ee3609d7284fd37c3cf0cea2401f319befd60a
ghc-options:
   "$locals": -fhide-source-paths -Wno-missing-home-modules
resolver: lts-23.0
nix:
  packages:
  - pkg-config
  - zlib
