flags:
  pandoc:
    trypandoc: false
    embed_data_files: true
packages:
- '.'
extra-deps:
- hslua-1.3.0
- hslua-module-path-0.1.0
- jira-wiki-markup-1.3.4
- citeproc-0.3.0.9
- relude-1.0.0.0
#- citeproc:
#  git: https://github.com/jgm/citeproc.git
#  commit: feb3b7580c6738eec3b23921f7c1739cfba611aa
ghc-options:
   "$locals": -fhide-source-paths -Wno-missing-home-modules
resolver: lts-17.5
nix:
  packages: [zlib]
