flags:
  pandoc:
    trypandoc: false
    embed_data_files: true
    static: false
  pandoc-citeproc:
    bibutils: true
    embed_data_files: true
    unicode_collation: false
    test_citeproc: false
    debug: false
packages:
- '.'
extra-deps:
- pandoc-citeproc-0.16.3.1
#- pandoc-types-1.17.6.1
- texmath-0.11.3
- haddock-library-1.8.0
- skylighting-0.8.2.3
- skylighting-core-0.8.2.3
- regex-pcre-builtin-0.95.0.8.8.35
- doclayout-0.2.0.1
- HsYAML-0.2.0.0
- HsYAML-aeson-0.2.0.0
- doctemplates-0.7
- git: https://github.com/jgm/pandoc-types
  commit: 00f7bb79e79d7cfd3523880dbc64ba3ea46c3da2
ghc-options:
   "$locals": -fhide-source-paths -Wno-missing-home-modules
resolver: lts-14.6
