flags:
  pandoc:
    trypandoc: false
    embed_data_files: true
packages:
- '.'
extra-deps:
- pandoc-types-1.22
- rfc5051-0.2
- haddock-library-1.9.0
- skylighting-0.10.1
- skylighting-core-0.10.1
- hslua-1.1.2
- jira-wiki-markup-1.3.2
- HsYAML-aeson-0.2.0.0
- commonmark-0.1.1.2
- commonmark-extensions-0.2.0.4
- commonmark-pandoc-0.2.0.1
- doctemplates-0.9
# - citeproc-0.2.0.1
- citeproc:
  git: https://github.com/jgm/citeproc.git
  commit: a8193fe375fa2354049bf9a967ba3bad4b1ba053
ghc-options:
   "$locals": -fhide-source-paths -Wno-missing-home-modules
resolver: lts-16.23
nix:
  packages: [zlib]

