flags:
  pandoc:
    embed_data_files: true
  QuickCheck:
    old-random: false
packages:
- '.'
- 'pandoc-cli'
- 'pandoc-lua-engine'
- 'pandoc-server'
extra-deps:
- hslua-2.4.0
- hslua-module-system-1.2.3
- hslua-objectorientation-2.4.0
- hslua-packaging-2.3.2
- skylighting-core-0.14.7
- skylighting-0.14.7
- djot-0.1.2.3
- typst-symbols-0.1.9.1
- git: https://github.com/jgm/citeproc.git
  commit: 1a82c13ac1d8e9e07cf69fbf89ba2b57474b8e0f
- git: https://github.com/jgm/typst-hs.git
  commit: e6eb442bc0efbe3fcf8c1fe5f28be3f0fb278e8b
- git: https://github.com/jgm/texmath.git
  commit: 110322589698df20abf3f3a06c070271802ea598
ghc-options:
   "$locals": -fhide-source-paths -Wno-missing-home-modules
resolver: lts-24.9
nix:
  packages:
  - pkg-config
  - zlib
