flags:
  pandoc:
    trypandoc: false
    embed_data_files: true
    static: false
  pandoc-citeproc:
    bibutils: true
    embed_data_files: true
    unicode_collation: false
    test_citeproc: false
    debug: false
packages:
- '.'
extra-deps:
- pandoc-types-1.21
- pandoc-citeproc-0.17.0.1
- texmath-0.12.0.2
- haddock-library-1.9.0
- skylighting-0.8.5
- skylighting-core-0.8.5
- regex-pcre-builtin-0.95.1.2.8.43
- regex-base-0.94.0.0
- doclayout-0.3
- emojis-0.1
- hslua-1.1.2
- jira-wiki-markup-1.3.2
- HsYAML-0.2.1.0
- HsYAML-aeson-0.2.0.0
- doctemplates-0.8.2
- commonmark-0.1.0.1
- commonmark-extensions-0.2.0.1
- commonmark-pandoc-0.2.0.0

ghc-options:
   "$locals": -fhide-source-paths -Wno-missing-home-modules
resolver: lts-14.6
nix:
  packages: [zlib]
