flags:
  pandoc:
    trypandoc: false
    embed_data_files: false
    old-locale: false
    network-uri: true
packages:
- '.'
extra-deps:
- pandoc-types-1.17.2
- texmath-0.9.4.2
- hslua-0.8.0
- skylighting-0.4
- cmark-gfm-0.1.1
- QuickCheck-2.10.0.1
- tasty-quickcheck-0.9.1
- haddock-library-1.4.3
resolver: lts-9.1
