flags:
  pandoc:
    embed_data_files: true
  QuickCheck:
    old-random: false
packages:
- '.'
- 'pandoc-cli'
- 'pandoc-lua-engine'
- 'pandoc-server'
extra-deps:
- lpeg-1.1.0
- tls-2.1.0
- crypton-connection-0.4.1
- toml-parser-2.0.1.0
- skylighting-0.14.3
- doclayout-0.5
- doctemplates-0.11.0.1
- hslua-module-doclayout-1.2.0
- djot-0.1.2.2
- commonmark-0.2.6.1
- typst-symbols-0.1.7
- git: https://github.com/jgm/skylighting.git
  commit: 2b6876018a903207c7a9093c5c63b00a4d0980be
  subdirs: [skylighting-core, skylighting-format-blaze-html]
- git: https://github.com/jgm/texmath.git
  commit: 4666e68eb1b640d69dc5261748bfe716e3b212c9
- git: https://github.com/jgm/typst-hs.git
  commit: 5a50154c958d09c06fd884dcc4519403f7904bc1
- git: https://github.com/pandoc/pandoc-lua-marshal
  commit: 2dc58d431bb3e4d55999db03c470fbf32970b3d5
- git: https://github.com/jgm/commonmark-hs.git
  commit: 1fddc913b31487571b12fd0ac99d4a0ab00acd34
  subdirs: [commonmark-extensions, commonmark-pandoc]

ghc-options:
   "$locals": -fhide-source-paths -Wno-missing-home-modules
resolver: lts-22.33
nix:
  packages:
  - pkg-config
  - zlib
