flags:
  pandoc:
    embed_data_files: true
  QuickCheck:
    old-random: false
packages:
- '.'
- 'pandoc-cli'
- 'pandoc-lua-engine'
- 'pandoc-server'
extra-deps:
- tls-2.1.5
ghc-options:
   "$locals": -fhide-source-paths -Wno-missing-home-modules
resolver: lts-23.0
nix:
  packages:
  - pkg-config
  - zlib
