flags:
  pandoc:
    trypandoc: false
    https: true
    embed_data_files: false
    old-locale: false
    network-uri: true
packages:
- '.'
extra-deps:
- doctemplates-0.1.0.2
- pandoc-types-1.17.0.4
- skylighting-0.1.1.4
- texmath-0.9
resolver: lts-7.14
