flags:
  pandoc:
    trypandoc: false
    embed_data_files: true
  QuickCheck:
    old-random: false
packages:
- '.'
extra-deps:
- commonmark-0.2.1
- commonmark-pandoc-0.2.1.1
- skylighting-core-0.11
- skylighting-0.11
- doctemplates-0.10
- texmath-0.12.3.1
- git: https://github.com/argent0/pandoc-types
  commit: 5b32019746d1692c593c080f9a8ee45c7d25ecba
- git: https://github.com/jgm/citeproc.git
  commit: b27201c3ac48ffd2853f77152df19b6e2cf36987
ghc-options:
   "$locals": -fhide-source-paths -Wno-missing-home-modules
resolver: lts-18.0
nix:
  packages: [zlib]


