flags:
  pandoc:
    trypandoc: false
    embed_data_files: true
  QuickCheck:
    old-random: false
packages:
- '.'
extra-deps:
- skylighting-core-0.12
- skylighting-0.12
- doctemplates-0.10
- emojis-0.1.2
- doclayout-0.3.1.1
- hslua-2.0.0
- hslua-classes-2.0.0
- hslua-core-2.0.0
- hslua-marshalling-2.0.0
- hslua-module-path-1.0.0
- hslua-module-system-1.0.0
- hslua-module-text-1.0.0
- hslua-module-version-1.0.0
- hslua-objectorientation-2.0.0
- hslua-packaging-2.0.0
- lua-2.0.0
- tasty-hslua-1.0.0
- tasty-lua-1.0.0
- pandoc-types-1.22.1
- texmath-0.12.3.2
- git: https://github.com/jgm/citeproc.git
  commit: 673a7fb643d24a3bb0f60f8f29e189c0ba7ef15b
- git: https://github.com/jgm/commonmark-hs.git
  commit: 7d34a747cd2d8668451909a722eb9ce16d1f4852
  subdirs: [commonmark, commonmark-pandoc]
ghc-options:
   "$locals": -fhide-source-paths -Wno-missing-home-modules
resolver: lts-18.10
nix:
  packages: [zlib]
