flags:
  pandoc:
    trypandoc: false
    https: true
    embed_data_files: false
    old-locale: false
    network-uri: true
packages:
- '.'
extra-deps:
- hslua-aeson-0.1.0.2
- skylighting-0.3.1
- texmath-0.9.3
resolver: lts-8.4
