blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/jgm/pandoc/discussions
    about: "Discussion forum for pandoc"
  - name: Contributing Guidelines
    url: https://pandoc.org/CONTRIBUTING.html
    about: "Guidelines for submitting bug reports and code improvements"

