#!/bin/sh
cputype=`/usr/sbin/sysctl -n hw.cputype`
sixtyfourbit=`/usr/sbin/sysctl -n hw.cpu64bit_capable`

if [ "x$cputype" != "x7" ] # x86
then
  exit 112
fi

if [ "x$sixtyfourbit" != "x1" ] # 64 bit
then
  exit 113
fi

