.TH PANDOC 1 "AUGUST 2006" Linux "User Manuals"
.SH NAME
html2markdown \- converts HTML to markdown-formatted text
.SH SYNOPSIS
.B html2markdown [input-file or URL]
.SH DESCRIPTION
.B html2markdown 
converts input-file (or text from STDIN) or URL from HTML to 
markdown-formatted plain text.  Uses an available program
(e.g. wget, w3m, lynx or curl) to fetch the URL.
.SH AUTHOR
John MacFarlane <jgm at berkeley.edu>
.SH "SEE ALSO"
pandoc (1), markdown2html (1), markdown2latex (1), latex2markdown (1), markdown2pdf (1)

