.TH PANDOC 1 "November 1, 2006" Linux "User Manuals"
.SH NAME
html2markdown \- converts HTML to markdown-formatted text
.SH SYNOPSIS
\fBhtml2markdown\fR [ \fIinput-file\fR or \fIURL\fR ]
.SH DESCRIPTION
\fBhtml2markdown\fR converts \fIinput-file\fR or \fIURL\fR 
(or text from STDIN) from HTML to  markdown-formatted plain text.
It uses an available program (e.g. wget, w3m, lynx or curl) to fetch
the contents of the URL. 
.PP
\fBhtml2markdown\fR is a wrapper for \fBpandoc\fR.
.SH OPTIONS
.TP
.B \-\-
Any options appearing after ` \-\- ' on the command line will be passed
directly to \fBpandoc\fR.  See \fBpandoc\fR(1) for a list of options
that may be used.  Options specified in this way will override
PANDOC_OPTS (see below).  Example:
.IP
html2markdown input.txt -- -R
.SH ENVIRONMENT
Any command-line options contained in the PANDOC_OPTS environment variable
will be passed directly to \fBpandoc\fR.  See \fBpandoc\fR(1)
for a list of options that may be used.
.SH "SEE ALSO"
\fBpandoc\fR(1),
\fBmarkdown2html\fR(1),
\fBmarkdown2latex\fR(1),
\fBlatex2markdown\fR(1),
\fBmarkdown2pdf\fR(1)
.SH AUTHOR
John MacFarlane
