.TH PANDOC 1 "November 1, 2006" Linux "User Manuals"
.SH NAME
latex2markdown \- converts LaTeX to markdown-formatted text
.SH SYNOPSIS
.B latex2markdown 
[
.I input-file
]
.SH DESCRIPTION
.I latex2markdown 
converts 
.I input-file 
(or text from STDIN) from LaTeX to markdown-formatted plain text.
.SH "SEE ALSO"
\fBpandoc\fR(1),
\fBmarkdown2html\fR(1),
\fBhtml2markdown\fR(1),
\fBmarkdown2latex\fR(1),
\fBmarkdown2pdf\fR(1)
.SH AUTHOR
John MacFarlane
