.TH PANDOC 1 "November 1, 2006" Linux "User Manuals"
.SH NAME
latex2markdown \- converts LaTeX to markdown-formatted text
.SH SYNOPSIS
\fBlatex2markdown\fR [ \fIinput-file\fR ]
.SH DESCRIPTION
\fBlatex2markdown\fR converts \fIinput-file\fR
(or text from STDIN) from LaTeX to markdown-formatted plain text.
.SH ENVIRONMENT
Any command-line options contained in the PANDOC_OPTS environment variable
will be passed to \fBpandoc\fR by this wrapper script.  See \fBpandoc\fR(1)
for a list of options that may be used.
.SH "SEE ALSO"
\fBpandoc\fR(1),
\fBmarkdown2html\fR(1),
\fBhtml2markdown\fR(1),
\fBmarkdown2latex\fR(1),
\fBmarkdown2pdf\fR(1)
.SH AUTHOR
John MacFarlane
