.TH PANDOC 1 "AUGUST 2006" Linux "User Manuals"
.SH NAME
markdown2latex \- converts markdown-formatted text to LaTeX 
.SH SYNOPSIS
.B markdown2latex [input-files]
.SH DESCRIPTION
.B markdown2latex 
converts input-files (or text from STDIN) from markdown-formatted
plain text to LaTeX.  If multiple files are specified, they will
be combined to make a single LaTeX document.
.SH AUTHOR
John MacFarlane <jgm at berkeley.edu>
.SH "SEE ALSO"
pandoc (1), markdown2html (1), html2markdown (1), latex2markdown (1),
markdown2pdf (1)

