.TH PANDOC 1 "November 1, 2006" Linux "User Manuals"
.SH NAME
markdown2html \- converts markdown-formatted text to HTML 
.SH SYNOPSIS
.B markdown2html 
[
.I input-files
]
.SH DESCRIPTION
.I markdown2html 
converts 
.I input-files 
(or text from STDIN) from markdown-formatted plain text to HTML. 
If multiple files are specified, they will be combined to make a single
HTML document.
.SH "SEE ALSO"
\fBpandoc\fR(1),
\fBhtml2markdown\fR(1),
\fBmarkdown2latex\fR(1),
\fBlatex2markdown\fR(1),
\fBmarkdown2pdf\fR(1)
.SH AUTHOR
John MacFarlane
