.TH PANDOC 1 "November 1, 2006" Linux "User Manuals"
.SH NAME
markdown2latex \- converts markdown-formatted text to LaTeX 
.SH SYNOPSIS
.B markdown2latex 
[
.I input-files
]
.SH DESCRIPTION
.I markdown2latex 
converts 
.I input-files 
(or text from STDIN) from markdown-formatted
plain text to LaTeX.  If multiple files are specified, they will
be combined to make a single LaTeX document.
.SH "SEE ALSO"
\fBpandoc\fR(1),
\fBmarkdown2html\fR(1),
\fBhtml2markdown\fR(1),
\fBlatex2markdown\fR(1),
\fBmarkdown2pdf\fR(1)
.SH AUTHOR
John MacFarlane
