.TH MARKDOWN2PDF 1 "December 15, 2006" Pandoc "User Manuals"
.SH NAME
markdown2pdf \- converts markdown-formatted text to PDF, using pdflatex 
.SH SYNOPSIS
\fBmarkdown2pdf\fR [\fIoptions\fR] [\fIinput-file\fR]...
.SH DESCRIPTION
\fBmarkdown2pdf\fR converts \fIinput\-file\fR (or text from standard 
input) from markdown\-formatted plain text to PDF, using \fBpdflatex\fR.
If no output filename is specified (using the \fB\-o\fR option),
the name of the output file is derived from the input file; thus, for
example, if the input file is \fIhello.txt\fR, the output file will be
\fIhello.pdf\fR.  If the input is read from STDIN and no output filename
is specified, the output file will be named \fIstdin.pdf\fR.  If multiple
input files are specified, they will be concatenated before conversion,
and the name of the output file will be derived from the first input file.
.PP
Input is assumed to be in the UTF\-8 character encoding.  If your
local character encoding is not UTF\-8, you should pipe input and
output through \fBiconv\fR:
.IP
.B iconv \-t utf\-8 input.txt | pandoc | iconv \-f utf\-8
.PP
\fBmarkdown2pdf\fR assumes that the 'unicode' and 'fancyvrb' packages
are in latex's search path.  If these packages are not included in your
latex setup, they can be obtained from <http://ctan.org>.
.PP
\fBmarkdown2pdf\fR is a wrapper around \fBpandoc\fR.
.SH OPTIONS
.TP
.B \-o FILE, \-\-output=FILE
Write output to \fIFILE\fR.
.TP
.B \-p, \-\-preserve-tabs
Preserve tabs instead of converting them to spaces.
.TP
.B \-\-tab-stop=\fITABSTOP\fB
Specify tab stop (default is 4).
.TP
.B \-\-strict
Use strict markdown syntax, with no extensions or variants.
.TP
.TP
.B \-N, \-\-number-sections
Number section headings in LaTeX output.  (Default is not to number them.)
.TP
.B \-H \fIFILE\fB, \-\-include-in-header=\fIFILE\fB
Include (LaTeX) contents of \fIFILE\fR at the end of the header.  Implies
\fB\-s\fR.
.TP
.B \-B \fIFILE\fB, \-\-include-before-body=\fIFILE\fB
Include (LaTeX) contents of \fIFILE\fR at the beginning of the document body.
.TP
.B \-A \fIFILE\fB, \-\-include-after-body=\fIFILE\fB
Include (LaTeX) contents of \fIFILE\fR at the end of the document body.
.TP
.B \-C \fIFILE\fB, \-\-custom-header=\fIFILE\fB
Use contents of \fIFILE\fR
as the LaTeX document header (overriding the default header, which can be
printed using '\fBpandoc \-D latex\fR').  Implies \fB-s\fR.
.TP
.B \-v, \-\-version
Print version.
.TP
.B \-h, \-\-help
Show usage message.
.SH "SEE ALSO"
\fBpandoc\fR(1),
\fBpdflatex\fR(1)
.SH AUTHOR
John MacFarlane and Recai Oktas
