.TH PANDOC 1 "AUGUST 2006" Linux "User Manuals"
.SH NAME
pandoc \- general markup converter
.SH SYNOPSIS
.B pandoc [options] [input-files]
.SH DESCRIPTION
.B pandoc
converts files from one markup format to another. It can read markdown
and (with some limitations) reStructuredText, HTML, and LaTeX, and it
can write markdown, reStructuredText, HTML, LaTeX, RTF, and S5 HTML
slide shows. 
.SH OPTIONS
For full usage information, including command-line options,
type
.B pandoc -h
.SH AUTHOR
John MacFarlane <jgm at berkeley.edu>
.SH "SEE ALSO"
markdown2html (1), html2markdown (1), markdown2latex (1), latex2markdown (1), markdown2pdf (1)

