flags:
  pandoc:
    trypandoc: false
    https: true
    embed_data_files: true
    old-locale: false
    network-uri: true
  pandoc-citeproc:
    bibutils: true
    embed_data_files: true
    unicode_collation: false
    test_citeproc: false
    debug: false
packages:
- '..'
- location:
    git: https://github.com/jgm/pandoc-citeproc.git
    commit: c53a27513318f1d23303ee27e46da9e7702c798e
  extra-dep: true
extra-deps:
resolver: lts-8.0
